export const browserCoreExamples = [
  "hello-io browser status",
  "hello-io browser start",
  "hello-io browser stop",
  "hello-io browser tabs",
  "hello-io browser open https://example.com",
  "hello-io browser focus abcd1234",
  "hello-io browser close abcd1234",
  "hello-io browser screenshot",
  "hello-io browser screenshot --full-page",
  "hello-io browser screenshot --ref 12",
  "hello-io browser snapshot",
  "hello-io browser snapshot --format aria --limit 200",
  "hello-io browser snapshot --efficient",
  "hello-io browser snapshot --labels",
];

export const browserActionExamples = [
  "hello-io browser navigate https://example.com",
  "hello-io browser resize 1280 720",
  "hello-io browser click 12 --double",
  'hello-io browser type 23 "hello" --submit',
  "hello-io browser press Enter",
  "hello-io browser hover 44",
  "hello-io browser drag 10 11",
  "hello-io browser select 9 OptionA OptionB",
  "hello-io browser upload /tmp/hello-io/uploads/file.pdf",
  'hello-io browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "hello-io browser dialog --accept",
  'hello-io browser wait --text "Done"',
  "hello-io browser evaluate --fn '(el) => el.textContent' --ref 7",
  "hello-io browser console --level error",
  "hello-io browser pdf",
];
